# Site wide configuration

title:            Big Blog of R Adventures
locale:           en_US
url:              http://michaelquinn32.github.io
description: >
    The personal blog of Michael Quinn, a Data Scientist who enjoys exploring
    new computational tools and teaching others. Tutorials, musings and other 
    adventures posted every now and then.

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-feed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Michael Quinn
  avatar: bio-photo.jpg
  bio: "Nerd dad who spends way too much time thinking about statistical computing, face-punching and other adventurous things."
  email: msquinn2@illinois.edu
  disqus-shortname: michaelquinn32
  twitter: michaelquinn32
  google:
    analytics: UA-69944402-1
    verify: xQogj-1c3Pnw2lZjKP6_vH0uz_COdCP7XwjJkepiAnc
    tagmanager: GTM-N4X4ZX
    ad-client:
    ad-slot:
  bing-verify:
  github: michaelquinn32
# stackoverflow: 5482627/michael-quinn
  linkedin: michaelquinn32

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "draft-posts", "post-elements", "michaelquinn32.github.io.Rproj", "_source", "build.R", "_cache"]
