---
layout: post
title: "How I Built this Site"
excerpt: "Or: How I transformed RStudio into a Blogging Platform, and how you can too!"
tags: [R, RStudio, Blog, Jekyll, Github Pages, Web Development]
comments: true
modified: 2015-10-30
image: 
    feature: sunset.jpg
    credit: Michael Quinn
---

I am not a web developer. I've blogged in the past, messed around with html a little and conceptualy understand style sheets, but that doesn't even bring me close to being capable of launching a website on my own. 

And yet, I built this a healthy portion of this website, on my own, using primary `git`, `markdown` and `CSS`. Right now, I'm writing this in Rstudio, and I'll build, test and deploy this post there too. In fact, at this point, I'm pretty sure I won't have to seriously investigate any more `css` or `html` as long as I don't get bored with my code syntax highlights (MOAR PRETTY COLORS).

This post will cover the process, failures and little amounts of code that wrote to get this blog up and running. Since I'm not a developer, a lot of this might not make much sense. It doesn't always make much sense to me. But it is a working webpage (I think?) stored and edited locally with tools familiar to most statisticians. If that something that suits your fancy, please read on.

# The plan

http://byverdu.github.io/how-to-host-your-blog-at-github-using-jekyll-and-poole/
